### ISSUE TITLE
Stuck in Infinite Loop

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/AColdWalk#13]
Thanks to [343e2b](https://github.com/shakna-israel/AColdWalk/commit/343e2bdc4b73d693021bb9cd2addfe7a7adb10aa), which fixed #12, the story is never called at all.

**Comment by shakna-israel** [comment]
Fixed for 0.0.2a as of [692f96](https://github.com/shakna-israel/AColdWalk/commit/692f9631391c4bcaa96be0f13587b9f9f3230b09)

Not fixing in master - wait till 0.0.2 is released.

**Comment by shakna-israel** [comment]
This is still hit and miss. The number of loops is redefined each time the function `play_loop()` is called.

**Comment by shakna-israel** [comment]
[Hack](https://github.com/shakna-israel/AColdWalk/commit/dbd1839cb041af35381c683369fcbe1b654cc2ee) written... Time to field test.

Definently a need for #7 soon.

**Comment by shakna-israel** [comment]
```
if loop != 'undefined':
    loop = random.randint(0,10)
```

Must be overtired.

This does ignore if the loop hasn't been set yet... But when `play_loop()` is called again, it's been set, and will vary every time again.

**Comment by shakna-israel** [comment]
[Another attempt](https://github.com/shakna-israel/AColdWalk/commit/532cf800f11993b200b4b48d71e814d10c93a84e).

Testing.

**Comment by shakna-israel** [comment]
Last commit was full of [syntax errors](https://github.com/shakna-israel/AColdWalk/commit/928e3e71d36ee0d092063513cd5df1f760a4331f).

**Comment by shakna-israel** [comment]
Log:

```
Your name is: Shakna
Body Warmth: 50%
Wood Stockpile: 100%
Health: 100%
Food Stockpile: 80%
Anxiety Level: 10%


Traceback (most recent call last):
  File "./AColdWalk.py", line 588, in <module>
    new_game()
  File "./AColdWalk.py", line 455, in new_game
    game_story()
  File "./AColdWalk.py", line 429, in game_story
    play_loop()
  File "./AColdWalk.py", line 395, in play_loop
    loop = loop - 1
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Issue: `loop` is set to `'undefined'`. Loop is treated as an `int` normally. Not `str`.

**Comment by shakna-israel** [comment]
As of [8cc8b4](https://github.com/shakna-israel/AColdWalk/commit/8cc8b4c646977f762525d8c7b7e8bec7e3766bac), the loop appears to work.

However, the gap between story events is null. - Keeping Issue Open until restored.

**Comment by shakna-israel** [comment]
Semi-fixed as of [f700f9](https://github.com/shakna-israel/AColdWalk/commit/f700f98ae3c2c856f267b1eb623597cff44d6a98)...

However, it makes it so that you can't lengthen the time between story events. So this issue isn't closing, but the game is playable.
