### ISSUE TITLE
New Game Error - name 'load' is not defined

### ISSUE THREAD

**Issue by shakna-israel** [shakna-israel/AColdWalk#9]
If load isn't created, the game still checks for it.

```
The rain just kept coming down, and the day kept getting colder.


... The cabin I, James, was staying in... I guess you could say it wasn't going to stay in one piece much longer.
Press enter to continue.

Traceback (most recent call last):
  File "./AColdWalk.py", line 473, in <module>
    new_game()
  File "./AColdWalk.py", line 343, in new_game
    game_story()
  File "./AColdWalk.py", line 293, in game_story
    if load == 'true':
NameError: global name 'load' is not defined
```

**Comment by shakna-israel** [comment]
Fixed as of [ab8613](https://github.com/shakna-israel/AColdWalk/commit/ab861311aecb62506f6534d5ac1a347e83823f20).
